script:
  # By default Travis CI executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

sudo: required

before_install:
  - chmod +x gradlew
  - sudo apt-get install lib32ncurses5

#notifications:
#  slack: literacyapp:HLjtHJdZ7DYJV2DlnDLrG6Gl
